In [1]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv('train.csv')

In [4]:
df1

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       76699 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    74804 non-null  float64
 10  Weather        76502 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB

In [18]:
df1['RoadType'].isnull().sum()

np.int64(0)

In [17]:
df1['RoadType']

0        Residential
1        Residential
2        Residential
3        Residential
4        Residential
            ...
77294    Residential
77295    Residential
77296    Residential
77297    Residential
77298    Residential
Name: RoadType, Length: 77299, dtype: object

In [19]:
df1['RoadType'].value_counts()

RoadType
Residential    69760
Street          3951
Highway         3588
Name: count, dtype: int64

In [20]:
df1['RoadType'].unique()

array(['Residential', 'Street', 'Highway'], dtype=object)

In [21]:
df1['Temperature'].isnull().sum()

np.int64(2495)

In [16]:
df1['RoadType'] = df1['RoadType'].fillna(method = 'ffill')

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_11488\1585254613.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['RoadType'] = df1['RoadType'].fillna(method = 'ffill')

In [22]:
df1['Temperature']

0              NaN
1        31.104565
2        25.919267
3              NaN
4        10.803667
           ...
77294    11.501664
77295    14.715254
77296    19.678860
77297    22.573958
77298     1.322034
Name: Temperature, Length: 77299, dtype: float64

In [23]:
mean_temp1 = df1['Temperature'].dropna().mean()

In [24]:
df1['Temperature'] = df1['Temperature'].fillna(mean_temp1)

In [25]:
df1['Temperature'].isnull().sum()

np.int64(0)

In [26]:
df1['Weather'].isnull().sum()

np.int64(797)

In [29]:
df1['Weather']

0          NaN
1        Sunny
2        Sunny
3        Rainy
4        Rainy
         ...
77294    Rainy
77295    Foggy
77296    Sunny
77297    Sunny
77298    Snowy
Name: Weather, Length: 77299, dtype: object

In [30]:
df1['Weather'] = df1['Weather'].fillna(method = 'ffill')

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_11488\1416815102.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['Weather'] = df1['Weather'].fillna(method = 'ffill')

In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       77299 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    77299 non-null  float64
 10  Weather        77299 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB

In [32]:
df1['Weather'] = df1['Weather'].fillna(method = 'bfill')

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_11488\2319324178.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['Weather'] = df1['Weather'].fillna(method = 'bfill')

In [37]:
df1['timestamp'] = pd.to_datetime(df1['timestamp'],format='%H:%M')

In [39]:
df1['hour'] = df1['timestamp'].dt.hour
df1['minute'] = df1['timestamp'].dt.minute

In [42]:
df1.drop('timestamp',axis=1,inplace=True)

In [43]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   demand         77299 non-null  float64
 4   RoadType       77299 non-null  object
 5   NumberofLanes  77299 non-null  int64
 6   LargeVehicles  77299 non-null  object
 7   Landmarks      77299 non-null  object
 8   Temperature    77299 non-null  float64
 9   Weather        77299 non-null  object
 10  hour           77299 non-null  int32
 11  minute         77299 non-null  int32
dtypes: float64(2), int32(2), int64(3), object(5)
memory usage: 6.5+ MB

In [49]:
cat_features = [
    'geohash',
    'RoadType',
    'LargeVehicles',
    'Landmarks',
    'Weather'
]

In [44]:
df1['day']

0        48
1        48
2        48
3        48
4        48
         ..
77294    49
77295    49
77296    49
77297    49
77298    49
Name: day, Length: 77299, dtype: int64

In [45]:
X = df1.drop('demand',axis =1)
y = df1['demand']

In [46]:
from sklearn.model_selection import train_test_split
X_train ,X_valid,y_train,y_valid = train_test_split(X,y,test_size=0.2,random_state=42)

In [63]:
from catboost import CatBoostRegressor
model = CatBoostRegressor(iterations=500,max_depth=8,learning_rate=0.1,verbose=100,random_state=42)
model.fit(X_train,y_train,cat_features=cat_features)

0:	learn: 0.1317468	total: 77.8ms	remaining: 38.8s
100:	learn: 0.0403478	total: 6.07s	remaining: 24s
200:	learn: 0.0364865	total: 12.4s	remaining: 18.5s
300:	learn: 0.0338914	total: 18.8s	remaining: 12.5s
400:	learn: 0.0324228	total: 25.1s	remaining: 6.2s
499:	learn: 0.0312195	total: 31.4s	remaining: 0us

CatBoostRegressor(iterations=500, learning_rate=0.1, loss_function='RMSE', max_depth=8, random_state=42, verbose=100)

In [64]:
predict = model.predict(X_valid)

In [66]:
from sklearn.metrics import r2_score
score = r2_score(y_pred=predict,y_true=y_valid)

In [67]:
score

0.941235964952225

In [54]:
df2 = pd.read_csv('test.csv')

In [55]:
df2

,Index,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,49,2:15,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02z9,49,2:15,Residential,1,Not Allowed,No,6.476213,Snowy
2,2,qp02yf,49,2:15,Residential,3,Allowed,Yes,22.318203,Sunny
3,3,qp02z6,49,2:15,Residential,2,Not Allowed,Yes,NaN,Rainy
4,4,qp02zd,49,2:15,Residential,1,Not Allowed,No,18.266162,Foggy
...,...,...,...,...,...,...,...,...,...,...
41773,41773,qp0d4q,49,13:45,Street,1,Not Allowed,Yes,19.588991,Sunny
41774,41774,qp0d4w,49,13:45,Residential,2,Not Allowed,Yes,10.735538,Rainy
41775,41775,qp0dhq,49,13:45,Residential,2,Not Allowed,Yes,13.223750,Rainy
41776,41776,qp0dhw,49,13:45,Residential,2,Not Allowed,Yes,12.510917,Rainy
41777,41777,qp0djq,49,13:45,Residential,2,Not Allowed,Yes,20.363693,Sunny

In [69]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41778 entries, 0 to 41777
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          41778 non-null  int64
 1   geohash        41778 non-null  object
 2   day            41778 non-null  int64
 3   timestamp      41778 non-null  object
 4   RoadType       41778 non-null  object
 5   NumberofLanes  41778 non-null  int64
 6   LargeVehicles  41778 non-null  object
 7   Landmarks      41778 non-null  object
 8   Temperature    41778 non-null  float64
 9   Weather        41778 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 3.2+ MB

In [57]:
mean_temp2 = df2['Temperature'].dropna().sum()

In [58]:
df2['Temperature'] = df2['Temperature'].fillna(mean_temp2)

In [59]:
df2['RoadType'] = df2['RoadType'].fillna(method='ffill')

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_11488\2763381426.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['RoadType'] = df2['RoadType'].fillna(method='ffill')

In [61]:
df2['RoadType'] = df2['RoadType'].fillna(method='bfill')

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_11488\4057498598.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['RoadType'] = df2['RoadType'].fillna(method='bfill')

In [68]:
df2['Weather'] =df2['Weather'].fillna(method = 'bfill')

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_11488\2676297824.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['Weather'] =df2['Weather'].fillna(method = 'bfill')

In [70]:
df2['timestamp'] = pd.to_datetime(df2['timestamp'],format='%H:%M')

In [71]:
df2['hour'] = df2['timestamp'].dt.hour
df2['minute'] = df2['timestamp'].dt.minute

In [72]:
df2.drop('timestamp',axis=1,inplace=True)

In [75]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41778 entries, 0 to 41777
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          41778 non-null  int64
 1   geohash        41778 non-null  object
 2   day            41778 non-null  int64
 3   RoadType       41778 non-null  object
 4   NumberofLanes  41778 non-null  int64
 5   LargeVehicles  41778 non-null  object
 6   Landmarks      41778 non-null  object
 7   Temperature    41778 non-null  float64
 8   Weather        41778 non-null  object
 9   hour           41778 non-null  int32
 10  minute         41778 non-null  int32
 11  demand         41778 non-null  float64
dtypes: float64(2), int32(2), int64(3), object(5)
memory usage: 3.5+ MB

In [74]:
df2['demand'] = model.predict(df2)

In [79]:
submission = pd.DataFrame({
    'Index' : df2['Index'],
    'demand' : df2['demand']
})

In [80]:
submission.to_csv('submission.csv',index=False)